version: '3.8'

services:
  app:
    image: masterziii/sca-project-frontend:latest
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src