# syntax=docker/dockerfile:1

# Multi-stage build
FROM node:14.18-alpine as build

WORKDIR /usr/src/app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

# -----------------
FROM nginx:1.21.3-alpine

COPY --from=build /usr/src/app/build /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf