# syntax=docker/dockerfile:1
# Dockerfile for development

# use an alpine base image to reduce image size
FROM node:14.18-alpine

# create app directory
WORKDIR /usr/src/app

# copy dependencies to serve as a cache layer if no new dependencies are added
COPY package.json .

# install dependencies
RUN npm install

# copy entire app directory
COPY . .

EXPOSE 4000

CMD ["npm", "start"]
