apiVersion: v1
kind: Service
metadata:
  name: faceapp-frontend-lb
spec:
  type: LoadBalancer
  selector: 
    app: faceapp-frontend
  ports:        
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: faceapp-frontend

spec:  
  selector:
    matchLabels: 
      app: faceapp-frontend

  replicas: 1
      
  template:
    metadata: 
      labels: 
        app: faceapp-frontend
    spec: 
      containers:
        - name: faceapp-frontend
          image: masterziii/sca-project-frontend:latest
          ports:
            containerPort: 80
